name: Build and publish
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install and Build
        run: |
          npm ci
          npm run build
          cp -r jsdoc build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        
        with:
          branch: gh-pages
          folder: build
          
      # Runs a single command using the runners shell
      - run: printf Deployed!